In [33]:
import pandas as pd
import numpy as np

In [34]:
import os

# set path
data_path = os.path.abspath('') + "/raw/details.xlsx"

df_distri_loc_area_repre = pd.read_excel(data_path, sheet_name = "Distri x loc x area x repre")
df_representantes = pd.read_excel(data_path, sheet_name = "Representantes")

### Exploracion datos

In [35]:
df_representantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Distrito        58 non-null     object
 1   Area_Actuacion  58 non-null     object
 2   Nombre          58 non-null     object
 3   RTV/DTM         58 non-null     object
 4   e-Mail          58 non-null     object
 5   Celular         57 non-null     object
 6   Unnamed: 6      0 non-null      float64
 7   Unnamed: 7      0 non-null      float64
 8   Unnamed: 8      0 non-null      float64
 9   Unnamed: 9      0 non-null      float64
 10  Unnamed: 10     0 non-null      float64
 11  Unnamed: 11     7 non-null      object
 12  Unnamed: 12     1 non-null      object
 13  Unnamed: 13     7 non-null      object
 14  Unnamed: 14     7 non-null      object
 15  Unnamed: 15     7 non-null      object
 16  Unnamed: 16     7 non-null      object
 17  Unnamed: 17     2 non-null      object
 18  Unnamed: 18     2 non-null      object
 19  Unnamed: 19     7 non-null      object
 20  Unnamed: 20     7 non-null      object
 21  Unnamed: 21     7 non-null      object
dtypes: float64(5), object(17)
memory usage: 12.0+ KB

In [36]:
# Eliminamos columnas rotas

column_index_to_stop = 6  # Adjust this to the desired column index
columns_to_delete = df_representantes.columns.tolist()[column_index_to_stop:]

df_representantes = df_representantes.drop(columns=columns_to_delete, axis=1)

In [37]:
df_representantes.shape

(69, 6)

In [38]:
df_representantes.head()

,Distrito,Area_Actuacion,Nombre,RTV/DTM,e-Mail,Celular
0,NOA-NEA,SANTA FE NORTE,VACANTE,RTV,VACANTE,ZZZZZZ
1,NOA-NEA,"TUCUMAN, CATAMARCA Y SANTIAGO OESTE",FEDERICO CARRIZO,RTV,federico.carrizo@basf.com,+54 938 15536044
2,NOA-NEA,"CORRIENTES, MISIONES Y NORTE DE ENTRE RIOS",TERENZIO VILLARRAZA FAVIO JOSE,RTV,favio.terenzio@basf.com,+54 937 94335022
3,NOA-NEA,SALTA Y JUJUY,CAZADO RODRIGO GABRIEL,RTV,rodrigo-gabriel.cazado@basf.com,+54 938 77408214
4,NOA-NEA,CHACO SUROESTE,BESTANGA IVAN NAHUEL,RTV,ivan.bestanga@basf.com,+54 937 31542623

------------------------------------------------

In [39]:
df_distri_loc_area_repre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   DISTRIBUIDOR BASF          320 non-null    object
 1   Provincia                  320 non-null    object
 2   localidad                  320 non-null    object
 3   Departamento / Partido     318 non-null    object
 4   pedania                    318 non-null    object
 5   distrito                   320 non-null    object
 6   √ÅREA ACTUACION RTV NOMBRE  320 non-null    object
 7   NOMBRE RTV                 317 non-null    object
 8   AREA ACTUACION DTM         319 non-null    object
 9   NOMBRE DTM                 317 non-null    object
dtypes: object(10)
memory usage: 25.1+ KB

In [40]:
df_RTV = df_distri_loc_area_repre[df_distri_loc_area_repre.columns.drop(list(df_distri_loc_area_repre.filter(regex='DTM')))]
df_DTM = df_distri_loc_area_repre[df_distri_loc_area_repre.columns.drop(list(df_distri_loc_area_repre.filter(regex='RTV')))]

In [41]:
df_DTM.head()

,DISTRIBUIDOR BASF,Provincia,localidad,Departamento / Partido,pedania,distrito,AREA ACTUACION DTM,NOMBRE DTM
0,SINER SA,SANTA FE,CERES,SAN CRISTOBAL,CERES,NOA-NEA,SANTA FE NORTE,MAURICIO MUCHUT
1,FG AGRO,ENTRE RIOS,CONCORDIA,CONCORDIA,CONCORDIA,NOA-NEA,LITORAL,MAURICIO MUCHUT
2,MAS AGRO CENTRO S.A.,CORDOBA,SANTA ROSA DE RIO PRIMERO,RIO PRIMERO,SANTA SOSA,PHC,CORDOBA NORTE,DANIEL ULLA
3,TERRA VERDE AGROINSUMOS SA,CORDOBA,VILLA MARIA,GENERAL SAN MARTIN,VILLA MARIA,PHC,CORDOBA CENTRO,SORAYA MARITANO
4,UNION AGRICOLA DE AVELLANEDA COOP.,SANTA FE,GUADALUPE NORTE,GENERAL OBLIGADO,GUADALUPE NORTE,NOA-NEA,SANTA FE NORTE,MAURICIO MUCHUT

In [42]:
df_RTV.head()

,DISTRIBUIDOR BASF,Provincia,localidad,Departamento / Partido,pedania,distrito,√ÅREA ACTUACION RTV NOMBRE,NOMBRE RTV
0,SINER SA,SANTA FE,CERES,SAN CRISTOBAL,CERES,NOA-NEA,SANTA FE NORTE,FAVIO TERENZIO VILLARRAZA
1,FG AGRO,ENTRE RIOS,CONCORDIA,CONCORDIA,CONCORDIA,NOA-NEA,LITORAL,FAVIO TERENZIO VILLARRAZA
2,MAS AGRO CENTRO S.A.,CORDOBA,SANTA ROSA DE RIO PRIMERO,RIO PRIMERO,SANTA SOSA,PHC,CORDOBA NORTE,IGNACIO REYNOSO
3,TERRA VERDE AGROINSUMOS SA,CORDOBA,VILLA MARIA,GENERAL SAN MARTIN,VILLA MARIA,PHC,CORDOBA CENTRO,EVELYN BISCHOFF
4,UNION AGRICOLA DE AVELLANEDA COOP.,SANTA FE,GUADALUPE NORTE,GENERAL OBLIGADO,GUADALUPE NORTE,NOA-NEA,SANTA FE NORTE,FAVIO TERENZIO VILLARRAZA

## Agregrar informacion de contacto

**Objetivo:** traer la informacion de contacto del df_representantes a el df_distri_loc_area_repre. 

Pasos:
* Separar columna de nombres en nombre y apellido en el df_representates.
* Separar columna de nombres en nombre y apellido en df_rtv y df_dtm
* tratar de unir

In [43]:
# Funcion para generar split de apellidos
def split_name(name):
    
    words = name.split()
    if len(words) == 2:
        # If there are exactly two words, split by the first space
        return words[0], words[1]
    elif len(words) > 2:
        # return first and last word
        return words[0], words[-1]
        #return ' '.join(words[:2]), ' '.join(words[2:]) # If there are more than two words, split by the second space
    else:
        # If there is only one word (just in case), return the word and an empty string
        return words[0], ''

### Representates

In [44]:
df_representantes[df_representantes['Nombre'].apply(lambda x: isinstance(x, float))]

   Distrito Area_Actuacion Nombre RTV/DTM e-Mail  Celular
58      NaN            NaN    NaN     NaN     NaN     NaN
59      NaN            NaN    NaN     NaN     NaN     NaN
60      NaN            NaN    NaN     NaN     NaN     NaN
61      NaN            NaN    NaN     NaN     NaN     NaN
62      NaN            NaN    NaN     NaN     NaN     NaN
63      NaN            NaN    NaN     NaN     NaN     NaN
64      NaN            NaN    NaN     NaN     NaN     NaN
65      NaN            NaN    NaN     NaN     NaN     NaN
66      NaN            NaN    NaN     NaN     NaN     NaN
67      NaN            NaN    NaN     NaN     NaN     NaN
68      NaN            NaN    NaN     NaN     NaN     NaN

In [45]:
df_representantes.dropna(axis = 0, inplace = True)

In [46]:
# Separamos en nombre y apellido los representates en 'Representates'
df_representantes[['apellido', 'nombre']] = df_representantes['Nombre'].apply(split_name).apply(pd.Series)
df_representantes.head()

,Distrito,Area_Actuacion,Nombre,RTV/DTM,e-Mail,Celular,apellido,nombre
0,NOA-NEA,SANTA FE NORTE,VACANTE,RTV,VACANTE,ZZZZZZ,VACANTE,
1,NOA-NEA,"TUCUMAN, CATAMARCA Y SANTIAGO OESTE",FEDERICO CARRIZO,RTV,federico.carrizo@basf.com,+54 938 15536044,FEDERICO,CARRIZO
2,NOA-NEA,"CORRIENTES, MISIONES Y NORTE DE ENTRE RIOS",TERENZIO VILLARRAZA FAVIO JOSE,RTV,favio.terenzio@basf.com,+54 937 94335022,TERENZIO,JOSE
3,NOA-NEA,SALTA Y JUJUY,CAZADO RODRIGO GABRIEL,RTV,rodrigo-gabriel.cazado@basf.com,+54 938 77408214,CAZADO,GABRIEL
4,NOA-NEA,CHACO SUROESTE,BESTANGA IVAN NAHUEL,RTV,ivan.bestanga@basf.com,+54 937 31542623,BESTANGA,NAHUEL

---

### df_rtv // df_dtm

In [47]:
df_RTV.dropna(axis = 0, inplace = True)
df_DTM.dropna(axis = 0, inplace = True)

/tmp/ipykernel_20274/3402535792.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_RTV.dropna(axis = 0, inplace = True)
/tmp/ipykernel_20274/3402535792.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_DTM.dropna(axis = 0, inplace = True)

In [48]:
df_RTV[['nombre', 'apellido']] = df_RTV['NOMBRE RTV']. apply(split_name).apply(pd.Series)

/tmp/ipykernel_20274/3548748097.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_RTV[['nombre', 'apellido']] = df_RTV['NOMBRE RTV']. apply(split_name).apply(pd.Series)
/tmp/ipykernel_20274/3548748097.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_RTV[['nombre', 'apellido']] = df_RTV['NOMBRE RTV']. apply(split_name).apply(pd.Series)

In [49]:
df_RTV.head()

,DISTRIBUIDOR BASF,Provincia,localidad,Departamento / Partido,pedania,distrito,√ÅREA ACTUACION RTV NOMBRE,NOMBRE RTV,nombre,apellido
0,SINER SA,SANTA FE,CERES,SAN CRISTOBAL,CERES,NOA-NEA,SANTA FE NORTE,FAVIO TERENZIO VILLARRAZA,FAVIO,VILLARRAZA
1,FG AGRO,ENTRE RIOS,CONCORDIA,CONCORDIA,CONCORDIA,NOA-NEA,LITORAL,FAVIO TERENZIO VILLARRAZA,FAVIO,VILLARRAZA
2,MAS AGRO CENTRO S.A.,CORDOBA,SANTA ROSA DE RIO PRIMERO,RIO PRIMERO,SANTA SOSA,PHC,CORDOBA NORTE,IGNACIO REYNOSO,IGNACIO,REYNOSO
3,TERRA VERDE AGROINSUMOS SA,CORDOBA,VILLA MARIA,GENERAL SAN MARTIN,VILLA MARIA,PHC,CORDOBA CENTRO,EVELYN BISCHOFF,EVELYN,BISCHOFF
4,UNION AGRICOLA DE AVELLANEDA COOP.,SANTA FE,GUADALUPE NORTE,GENERAL OBLIGADO,GUADALUPE NORTE,NOA-NEA,SANTA FE NORTE,FAVIO TERENZIO VILLARRAZA,FAVIO,VILLARRAZA

In [50]:
df_DTM[['nombre', 'apellido']] = df_DTM['NOMBRE DTM ']. apply(split_name).apply(pd.Series)

/tmp/ipykernel_20274/2285158550.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_DTM[['nombre', 'apellido']] = df_DTM['NOMBRE DTM ']. apply(split_name).apply(pd.Series)
/tmp/ipykernel_20274/2285158550.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_DTM[['nombre', 'apellido']] = df_DTM['NOMBRE DTM ']. apply(split_name).apply(pd.Series)

In [51]:
df_DTM.head()

,DISTRIBUIDOR BASF,Provincia,localidad,Departamento / Partido,pedania,distrito,AREA ACTUACION DTM,NOMBRE DTM,nombre,apellido
0,SINER SA,SANTA FE,CERES,SAN CRISTOBAL,CERES,NOA-NEA,SANTA FE NORTE,MAURICIO MUCHUT,MAURICIO,MUCHUT
1,FG AGRO,ENTRE RIOS,CONCORDIA,CONCORDIA,CONCORDIA,NOA-NEA,LITORAL,MAURICIO MUCHUT,MAURICIO,MUCHUT
2,MAS AGRO CENTRO S.A.,CORDOBA,SANTA ROSA DE RIO PRIMERO,RIO PRIMERO,SANTA SOSA,PHC,CORDOBA NORTE,DANIEL ULLA,DANIEL,ULLA
3,TERRA VERDE AGROINSUMOS SA,CORDOBA,VILLA MARIA,GENERAL SAN MARTIN,VILLA MARIA,PHC,CORDOBA CENTRO,SORAYA MARITANO,SORAYA,MARITANO
4,UNION AGRICOLA DE AVELLANEDA COOP.,SANTA FE,GUADALUPE NORTE,GENERAL OBLIGADO,GUADALUPE NORTE,NOA-NEA,SANTA FE NORTE,MAURICIO MUCHUT,MAURICIO,MUCHUT

-----

### Union

In [52]:
df_representantes.head()

,Distrito,Area_Actuacion,Nombre,RTV/DTM,e-Mail,Celular,apellido,nombre
0,NOA-NEA,SANTA FE NORTE,VACANTE,RTV,VACANTE,ZZZZZZ,VACANTE,
1,NOA-NEA,"TUCUMAN, CATAMARCA Y SANTIAGO OESTE",FEDERICO CARRIZO,RTV,federico.carrizo@basf.com,+54 938 15536044,FEDERICO,CARRIZO
2,NOA-NEA,"CORRIENTES, MISIONES Y NORTE DE ENTRE RIOS",TERENZIO VILLARRAZA FAVIO JOSE,RTV,favio.terenzio@basf.com,+54 937 94335022,TERENZIO,JOSE
3,NOA-NEA,SALTA Y JUJUY,CAZADO RODRIGO GABRIEL,RTV,rodrigo-gabriel.cazado@basf.com,+54 938 77408214,CAZADO,GABRIEL
4,NOA-NEA,CHACO SUROESTE,BESTANGA IVAN NAHUEL,RTV,ivan.bestanga@basf.com,+54 937 31542623,BESTANGA,NAHUEL

In [53]:
df_representantes_RTV = df_representantes.loc[df_representantes["RTV/DTM"] == "RTV"]
df_representantes_DTM = df_representantes.loc[~(df_representantes["RTV/DTM"] == "RTV")]

#### RTV

##### Exact Match

In [54]:
merged_df = pd.merge(df_RTV, df_representantes_RTV, on=['nombre', 'apellido'], how='left')

In [55]:
merged_df[merged_df['Nombre'].isnull()]

,DISTRIBUIDOR BASF,Provincia,localidad,Departamento / Partido,pedania,distrito,√ÅREA ACTUACION RTV NOMBRE,NOMBRE RTV,nombre,apellido,Distrito,Area_Actuacion,Nombre,RTV/DTM,e-Mail,Celular
0,SINER SA,SANTA FE,CERES,SAN CRISTOBAL,CERES,NOA-NEA,SANTA FE NORTE,FAVIO TERENZIO VILLARRAZA,FAVIO,VILLARRAZA,NaN,NaN,NaN,NaN,NaN,NaN
1,FG AGRO,ENTRE RIOS,CONCORDIA,CONCORDIA,CONCORDIA,NOA-NEA,LITORAL,FAVIO TERENZIO VILLARRAZA,FAVIO,VILLARRAZA,NaN,NaN,NaN,NaN,NaN,NaN
4,UNION AGRICOLA DE AVELLANEDA COOP.,SANTA FE,GUADALUPE NORTE,GENERAL OBLIGADO,GUADALUPE NORTE,NOA-NEA,SANTA FE NORTE,FAVIO TERENZIO VILLARRAZA,FAVIO,VILLARRAZA,NaN,NaN,NaN,NaN,NaN,NaN
5,BAYA CASAL ENRIQUE M SA,ENTRE RIOS,GUALEGUAY,GUALEGUAY,GUALEGUAY,PHN,SANTA FE ROSARIO,HERNAN STAMBUCK,HERNAN,STAMBUCK,NaN,NaN,NaN,NaN,NaN,NaN
6,CAMEL AGRO SRL,BUENOS AIRES,ROJAS,ROJAS,ROJAS,PHS,BA CENTRO-NORTE,ADRIAN AMIONE,ADRIAN,AMIONE,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,QUINTAL AGROSS,ENTRE RIOS,PARANA,PARANA,PARANA,PHN,EERR CENTRO-SUR,MARCOS ANZULOVICH,MARCOS,ANZULOVICH,NaN,NaN,NaN,NaN,NaN,NaN
307,AZUL JACARANDA SA,BUENOS AIRES,PEHUAJO,PEHUAJO,PEHUAJO,PHS,BA NOROESTE,MARIA EUGENIA DUHALDE,MARIA,DUHALDE,NaN,NaN,NaN,NaN,NaN,NaN
308,AGRONORTE,SANTA FE,SAN FRANCISCO,CASTELLANOS,BAUER Y SIGEL,PHN,CORDOBA N.E. Y SANTA FE C.O.,HORACIO LOSANO,HORACIO,LOSANO,NaN,NaN,NaN,NaN,NaN,NaN
309,FG AGRO,ENTRE RIOS,SAN SALVADOR,SAN SALVADOR,SAN SALVADOR,PHN,EERR CENTRO-SUR,MARCOS ANZULOVICH,MARCOS,ANZULOVICH,NaN,NaN,NaN,NaN,NaN,NaN
310,LARTIRIGOYEN CIA S.A.,LA PAMPA,CATRILO,CATRILO,CATRILO,PHS,LA PAMPA,CLAUDIO SAENZ,CLAUDIO,SAENZ,NaN,NaN,NaN,NaN,NaN,NaN

198 registros siguen unmatched.

##### Fuzzy Matching

In [56]:
from fuzzywuzzy import fuzz, process

def fuzzy_merge(df1, df2, key1, key2, threshold=90):
    """
    df1 is the left table to join
    df2 is the right table to join
    key1 is the key column of df1
    key2 is the key column of df2
    threshold is how close the matches should be to return a match, based on Levenshtein distance
    """
    s = df2[key2].tolist()
    
    # Encuentro el match -> m devuelve una serie de pandas: ['(NOMBRE, # VECES QUE LO ENCUENTRA)']
    m = df1[key1].apply(lambda x: process.extractOne(x, s, score_cutoff=threshold))
    
    # Obtengo el nombre de df2 - debo transformar m.
    
    # Step 1: Quito parentesis
    m_clean = m.astype(str).str.strip('()')

    # Step 2: Separo string entre nombre y # de veces que encuentra
    df_split = m_clean.str.split(', ', expand=True)

    # Step 3: Solo me interesa el nombre
    match = df_split[[0]].rename(columns={0: 'Name'})
    
    df1['matches'] = match['Name'] # solo me quedo el nombre
    
    return df1

In [57]:
# Creamos merged set
merged_RTV = fuzzy_merge(df_RTV, df_representantes_RTV, 'NOMBRE RTV', 'Nombre', threshold=60)

/tmp/ipykernel_20274/2459021407.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['matches'] = match['Name'] # solo me quedo el nombre

In [58]:
merged_RTV[merged_RTV['matches'].isnull()]

Empty DataFrame
Columns: [DISTRIBUIDOR BASF, Provincia, localidad, Departamento / Partido, pedania, distrito, √ÅREA ACTUACION RTV NOMBRE, NOMBRE RTV, nombre, apellido, matches]
Index: []

In [59]:
# quitamos comillas
merged_RTV['matches'] = merged_RTV['matches'].str.replace("'"," ")

#  agregamos contacto
merged_RTV = merged_RTV.rename(columns={'matches': 'Nombre'})

# Limpiamos
merged_RTV['Nombre'] = merged_RTV['Nombre'].str.strip()
merged_RTV['Nombre'] = merged_RTV['Nombre'].str.replace(r'\s+', ' ', regex=True)

/tmp/ipykernel_20274/3529466315.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_RTV['matches'] = merged_RTV['matches'].str.replace("'"," ")

In [60]:
# Unimos tabla RTV
merged_RTV = pd.merge(merged_RTV, df_representantes_RTV, on = 'Nombre', how = 'left')

# Quitamos columnas adicionales
merged_RTV.drop(columns= ['nombre_y', 'apellido_y','NOMBRE RTV', 'Distrito', 'Area_Actuacion'], inplace= True)

#### DTM

In [61]:
# Creamos merged set
merged_DTM = fuzzy_merge(df_DTM, df_representantes_DTM, 'NOMBRE DTM ', 'Nombre', threshold=60)

/tmp/ipykernel_20274/2459021407.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['matches'] = match['Name'] # solo me quedo el nombre

In [62]:
merged_DTM[merged_DTM['matches'].isnull()]

Empty DataFrame
Columns: [DISTRIBUIDOR BASF, Provincia, localidad, Departamento / Partido, pedania, distrito, AREA ACTUACION DTM, NOMBRE DTM , nombre, apellido, matches]
Index: []

In [63]:
# quitamos comillas
merged_DTM['matches'] = merged_DTM['matches'].str.replace("'"," ")

#  agregamos contacto
merged_DTM = merged_DTM.rename(columns={'matches': 'Nombre'})

# Limpiamos
merged_DTM['Nombre'] = merged_DTM['Nombre'].str.strip()
merged_DTM['Nombre'] = merged_DTM['Nombre'].str.replace(r'\s+', ' ', regex=True)

/tmp/ipykernel_20274/1033637405.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_DTM['matches'] = merged_DTM['matches'].str.replace("'"," ")

In [66]:
# Unimos tabla RTV
merged_DTM = pd.merge(merged_DTM, df_representantes_DTM, on = 'Nombre', how = 'left')

# Quitamos columnas adicionales
merged_DTM.drop(columns= ['nombre_y', 'apellido_y','NOMBRE DTM ', 'Distrito', 'Area_Actuacion'], inplace= True)

In [69]:
merged_DTM

,DISTRIBUIDOR BASF,Provincia,localidad,Departamento / Partido,pedania,distrito,AREA ACTUACION DTM,nombre_x,apellido_x,Nombre,RTV/DTM,e-Mail,Celular
0,SINER SA,SANTA FE,CERES,SAN CRISTOBAL,CERES,NOA-NEA,SANTA FE NORTE,MAURICIO,MUCHUT,MUCHUT MAURICIO ESTEBAN,DTM,mauricio.muchut@basf.com,+54 934 82296464
1,FG AGRO,ENTRE RIOS,CONCORDIA,CONCORDIA,CONCORDIA,NOA-NEA,LITORAL,MAURICIO,MUCHUT,MUCHUT MAURICIO ESTEBAN,DTM,mauricio.muchut@basf.com,+54 934 82296464
2,MAS AGRO CENTRO S.A.,CORDOBA,SANTA ROSA DE RIO PRIMERO,RIO PRIMERO,SANTA SOSA,PHC,CORDOBA NORTE,DANIEL,ULLA,ULLA DANIEL JOSE,DTM,daniel.ulla@basf.com,+54 935 85070315
3,TERRA VERDE AGROINSUMOS SA,CORDOBA,VILLA MARIA,GENERAL SAN MARTIN,VILLA MARIA,PHC,CORDOBA CENTRO,SORAYA,MARITANO,MARITANO SORAYA,DTM,soraya.maritano@basf.com,+54 935 34250007
4,UNION AGRICOLA DE AVELLANEDA COOP.,SANTA FE,GUADALUPE NORTE,GENERAL OBLIGADO,GUADALUPE NORTE,NOA-NEA,SANTA FE NORTE,MAURICIO,MUCHUT,MUCHUT MAURICIO ESTEBAN,DTM,mauricio.muchut@basf.com,+54 934 82296464
...,...,...,...,...,...,...,...,...,...,...,...,...,...
311,RURAL CERES S.A,BUENOS AIRES,TANDIL,TANDIL,TANDIL,PHS,BA SUDESTE,FACUNDO,CAMERINI,CAMERINI ALEWAERTS FACUNDO,DTM,facundo.camerini@basf.com,ZZZZZZ
312,LA CASA DEL AGRO SA,CORDOBA,EL FUERTECITO,SAN JUSTO,ARROYITO,PHC,CORDOBA NORTE,DANIEL,ULLA,ULLA DANIEL JOSE,DTM,daniel.ulla@basf.com,+54 935 85070315
313,LA CASA DEL AGRO SA,CORDOBA,MARULL,SAN JUSTO,CONCEPCION,PHC,CORDOBA NORTE,DANIEL,ULLA,ULLA DANIEL JOSE,DTM,daniel.ulla@basf.com,+54 935 85070315
314,LA CASA DEL AGRO SA,CORDOBA,SANTA ROSA DE RIO PRIMERO,RIO PRIMERO,SANTA SOSA,PHC,CORDOBA NORTE,DANIEL,ULLA,ULLA DANIEL JOSE,DTM,daniel.ulla@basf.com,+54 935 85070315
315,TECNOCAMPO SA,CORDOBA,ALTA GRACIA,SANTA MARIA,ALTA GRACIA,PHC,CORDOBA NORTE,DANIEL,ULLA,ULLA DANIEL JOSE,DTM,daniel.ulla@basf.com,+54 935 85070315

---

### Exportamos datasets listos

In [73]:
# Create the "processed" folder if it doesn't exist
#if not os.path.exists('../processed'):
#   os.makedirs('processed')

path = os.path.abspath('') + "/processed/"

# Export merged_DTM to CSV
merged_DTM.to_csv(path + 'merged_DTM.csv', index=False)

# Export merged_RTV to CSV
merged_RTV.to_csv(path + 'merged_RTV.csv', index=False)